### ISSUE TITLE
Edit Profile pic-Nickname not working.

### ISSUE THREAD

**Issue by owen2kau** [Eltion/Tiktok-SSL-Pinning-Bypass#20] opened 2023-06-22 12:50 UTC
it seems tiktok can detect the bypasss or an irregularity in the App and disable certain features, trying the APK downloaded here and building my own from the latest APK gives the same result, it downloads videos and logs in ok using a MITM proxy but if attempting to change Profile pic or nickname it flags up errors from the TT Server like with the profile pic "Not so fast" and Nickname change, only 1 change allowed within 7 days and blocks the change) this happens with and without the MITM Proxy in place.  

uninstalling & Reverting back to the default app from the Play store resolves these issues but then of course it will not work with the MITM proxy.

**Comment by Eltion** [comment] 2023-06-24 14:38
Closing this issue as a duplicate of : https://github.com/Eltion/Tiktok-SSL-Pinning-Bypass/issues/9.
Please follow any updates there, I will try patching the apk with a custom frida-agent which would hopefully help with this problem.

**Closed by Eltion** 2023-06-24 14:38 UTC
